---
- ansible.builtin.import_tasks: pacman.yml
  tags: [packages, packages/pacman]

- ansible.builtin.import_tasks: pacman_reflector.yml
  tags: [packages, packages/pacman_reflector]

- ansible.builtin.import_tasks: aur.yml
  tags: [packages, packages/aur]

- ansible.builtin.import_tasks: flatpak.yml
  tags: [packages, packages/flatpak]

# - import_tasks: onedrive.yml
#   tags: [packages, packages/onedrive]
