---
- name: install pacman packages
  become: true
  community.general.pacman:
    update_cache: true
    name: "{{ packages_pacman + packages_pacman_extra }}"
    state: present

- name: configure pacman
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ pacman_config }}"
