---
# downloadupdates timer run "checkupdates -d" periodically, so updating packages becomes instant.

- name: install pacman-contrib (for checkupdates script)
  become: true
  community.general.pacman:
    name: pacman-contrib
    state: latest

- name: install downloadupdates systemd service and timer
  become: true
  ansible.builtin.template:
    src: downloadupdates/{{ item }}
    dest: /etc/systemd/system/{{ item }}
  loop:
    - downloadupdates.service
    - downloadupdates.timer

- name: enable and start downloadupdates timer
  become: true
  ansible.builtin.systemd:
    name: downloadupdates.timer
    enabled: true
    state: started
    daemon_reload: true
