---
- name: backup current pacman mirrorlist
  become: true
  ansible.builtin.copy:
    src: /etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist.backup
    force: false

- name: install reflector (pacman mirrorlist auto-updater)
  become: true
  community.general.pacman:
    name: reflector
    state: latest

- name: start reflector service (do NOT enable it)
  become: true
  ansible.builtin.systemd:
    name: reflector
    enabled: false
    state: started

- name: enable and start reflector timer
  become: true
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
