---
# Reference: https://wiki.archlinux.org/title/Zram

# To verify, run "cat /sys/module/zswap/parameters/enabled". The output should be "N".
- name: disable zswap (requires reboot)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!zswap.enabled=0).)*?)"$
    line: GRUB_CMDLINE_LINUX_DEFAULT="\1 zswap.enabled=0"
    backup: true
    backrefs: true
  notify: generate grub config

- name: install zram-generator
  become: true
  community.general.pacman:
    name: zram-generator
    state: present

- name: configure zram-generator
  become: true
  ansible.builtin.template:
    src: zram-generator.conf
    dest: /etc/systemd/zram-generator.conf
  notify:
    - restart zram service

- name: enable and start zram service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: systemd-zram-setup@zram0.service
    enabled: true
    state: started
