---
- name: git submodule update --init --recursive
  ansible.builtin.command: git submodule update --init --recursive
- name: set timezone
  become: true
  community.general.timezone:
    name: "{{ lookup('env', 'MY_TIMEZONE') }}"
  tags:
    - timezone

# https://vrgl.ir/kJLKL
# https://www.cyberciti.biz/cloud-computing/increase-your-linux-server-internet-speed-with-tcp-bbr-congestion-control/
# https://groups.google.com/g/bbr-dev/c/4jL4ropdOV8?pli=1
# https://github.com/systemd/systemd/issues/9725
- name: set TCP congestion control algorithm to "bbr"
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/20-bbr.conf
  loop:
    - name: net.ipv4.tcp_congestion_control
      value: bbr
    - name: net.core.default_qdisc
      value: fq_codel
  tags:
    - bbr

- { ansible.builtin.import_tasks: terminal/main.yml, tags: [terminal] }
- { ansible.builtin.import_tasks: vim.yml, tags: [vim] }
- { ansible.builtin.import_tasks: python.yml, tags: [python] }
- { ansible.builtin.import_tasks: proxy.yml, tags: [proxy] }
- { ansible.builtin.import_tasks: ssh.yml, tags: [ssh] }
- { ansible.builtin.import_tasks: git.yml, tags: [git] }
- { ansible.builtin.import_tasks: graphics.yml, tags: [graphics] }
- { ansible.builtin.import_tasks: audio.yml, tags: [audio] }
- { ansible.builtin.import_tasks: suspend.yml, tags: [suspend] }
- { ansible.builtin.import_tasks: wayland.yml, tags: [wayland] }
