---
- name: install vimrc
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vimrc"
    dest: ~/.vimrc
    state: link

- name: create ~/.vim/pack/plugins/start directory
  ansible.builtin.file:
    path: ~/.vim/pack/plugins/start
    state: directory
    recurse: true

- name: install vim plugin - lightline
  ansible.builtin.git:
    repo: git@github.com:itchyny/lightline.vim.git
    dest: ~/.vim/pack/plugins/start/lightline

- name: install vim plugin - vim-hybrid-material
  ansible.builtin.git:
    repo: git@github.com:kristijanhusak/vim-hybrid-material.git
    dest: ~/.vim/pack/plugins/start/colorscheme-hybrid-material

- name: install vim plugin - vim-colorscheme-primary
  ansible.builtin.git:
    repo: git@github.com:google/vim-colorscheme-primary.git
    dest: ~/.vim/pack/plugins/start/colorscheme-primary
