---
# https://wiki.archlinux.org/title/wayland#Detect_Xwayland_applications_visually
- name: install xeyes (to detect Xwayland applications)
  become: true
  community.general.pacman:
    name: xorg-xeyes
    state: latest

# https://wiki.archlinux.org/title/PipeWire#WebRTC_screen_sharing
# Test Page: https://mozilla.github.io/webrtc-landing/gum_test.html
- name: install required packages for webrtc screen sharing
  become: true
  community.general.pacman:
    name:
      - pipewire
      - wireplumber
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
    state: latest

- name: create wireplumber configuration directory
  ansible.builtin.file:
    path: ~/.config/wireplumber/wireplumber.conf.d
    state: directory

# https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2669#note_2362342
- name: fix webcam power consumption issue
  ansible.builtin.copy:
    dest: ~/.config/wireplumber/wireplumber.conf.d/10-disable-camera.conf
    content: |
      wireplumber.profiles = {
        main = {
          monitor.libcamera = disabled
        }
      }
  notify: restart wireplumber service

# https://wiki.archlinux.org/title/chromium#Native_Wayland_support
# https://www.reddit.com/r/archlinux/comments/13gtogn/comment/jstqvlt/
- name: enable native wayland support for chrome, chromium, and edge
  ansible.builtin.copy:
    content: --ozone-platform-hint=auto
    dest: ~/.config/{{ item }}
  loop:
    - chrome-flags.conf
    - chromium-flags.conf
    - microsoft-edge-stable-flags.conf # https://aur.archlinux.org/cgit/aur.git/tree/microsoft-edge-stable.sh?h=microsoft-edge-stable-bin

# To enable native wayland support for Electron apps, add `--ozone-platform-hint=auto` to the command running the app.
# To persist, you can add it to related `.desktop` file.
# https://wiki.archlinux.org/title/wayland#Electron

# Status of wayland support in JetBrains IDEs: https://youtrack.jetbrains.com/issue/JBR-3206
