---
# https://wiki.archlinux.org/title/Bluetooth
- name: install bluez
  become: true
  ansible.builtin.package:
    name: bluez
    state: latest

- name: enable and start bluetooth service
  become: true
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
    state: started
