---
- name: install gnome-tweaks
  become: true
  community.general.pacman:
    name: gnome-tweaks
    state: latest

- name: install extension dependencies
  become: true
  community.general.pacman:
    name: "{{ item.dependencies }}"
    state: latest
  when: "'dependencies' in item"
  loop: "{{ gnome_extensions }}"
  loop_control:
    label: "{{ item.id }} {{ item.dependencies | default([]) }}"

- name: install gnome extensions
  ansible.builtin.command:
    cmd: |
      busctl --user call
      org.gnome.Shell
      /org/gnome/Shell
      org.gnome.Shell.Extensions InstallRemoteExtension
      s "{{ item.id }}"
    creates: "{{ ('~/.local/share/gnome-shell/extensions', item.id) | path_join }}"
  loop: "{{ gnome_extensions }}"
  loop_control:
    label: "{{ item.id }}"

- name: configure gnome extensions
  gsettings:
    schemadir: ~/.local/share/gnome-shell/extensions/{{ item.0.id }}/schemas/
    schema: "{{ item.1.schema }}"
    key: "{{ item.1.key }}"
    value: "{{ item.1.value }}"
  loop: "{{ gnome_extensions|subelements('settings', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.id }} {{ item.1.schema }} {{ item.1.key }}"

#- name: clone/update Graphite-gtk-theme git repo
#  ansible.builtin.git:
#    repo: https://github.com/vinceliuice/Graphite-gtk-theme.git
#    dest: "~/.cache/ansible-gnome/graphite-gtk-theme"
#
#- name: install Graphite gtk theme
#  ansible.builtin.command: "~/.cache/ansible-gnome/graphite-gtk-theme/install.sh --tweaks nord rimless normal"
#
#- name: enable Graphite gtk theme
#  gsettings:
#    schema: org.gnome.desktop.interface
#    key: gtk-theme
#    value: Graphite-Light-nord

- name: install qogir icon theme
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: qogir-icon-theme
    state: present
- name: set cursor theme to "Qogir"
  gsettings:
    schema: org.gnome.desktop.interface
    key: cursor-theme
    value: Qogir-dark

- name: apply gnome settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ gnome_settings + gnome_settings_extra }}"

- name: install eog (Eye of Gnome) image viewer
  become: true
  community.general.pacman:
    name: eog
    state: latest
- name: apply eog settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ gnome_eog_settings }}"

- name: install nautilus file manager
  become: true
  community.general.pacman:
    name: nautilus
    state: latest
- name: apply file manager (nautilus) settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ gnome_nautilus_settings }}"

- name: install gnome-text-editor
  become: true
  community.general.pacman:
    name: gnome-text-editor
    state: latest
- name: apply gnome text editor settings
  gsettings:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ gnome_text_editor_settings }}"

# https://wiki.archlinux.org/title/GNOME/Keyring#Setup_gcr
# The SSH functionality is disabled by default in gnome-keyring-daemon builds since version 1:46.
# It has been moved into /usr/lib/user/gcr-ssh-agent, which is part of the gcr-4 package.
- name: Setup gcr
  block:
    # install gcr-4 package
    - name: install gnome gcr (https://gitlab.gnome.org/GNOME/gcr)
      become: true
      community.general.pacman:
        name: gcr-4
        state: latest

    # Enable the `gcr-ssh-agent.socket` systemd user unit.
    - name: enable gcr-ssh-agent.socket
      ansible.builtin.systemd:
        scope: user
        name: gcr-ssh-agent.socket
        enabled: true

    - name: create ~/.config/environment.d directory
      ansible.builtin.file:
        path: ~/.config/environment.d
        state: directory
        recurse: true

    # https://wiki.archlinux.org/title/Environment_variables#Per_Wayland_session
    - name: configure SSH_AUTH_SOCK environment variable
      ansible.builtin.copy:
        content: SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
        dest: ~/.config/environment.d/ssh-agent.conf
