---
gnome_extensions:
  # - id: Hide_Activities@shay.shayel.org # https://extensions.gnome.org/extension/744/hide-activities-button/
  # - id: sound-output-device-chooser@kgshank.net # https://extensions.gnome.org/extension/906/sound-output-device-chooser/
  - id: ProxySwitcher@flannaghan.com # https://extensions.gnome.org/extension/771/proxy-switcher/
  - id: appindicatorsupport@rgcjonas.gmail.com # https://extensions.gnome.org/extension/615/appindicator-support/
  # - id: hide-keyboard-layout@sitnik.ru # https://extensions.gnome.org/extension/2848/hide-keyboard-layout/
  - id: rocketbar@chepkun.github.com # https://extensions.gnome.org/extension/5180/rocketbar/
  - id: system-monitor-next@paradoxxx.zero.gmail.com # https://extensions.gnome.org/extension/3010/system-monitor-next/
  - id: ddterm@amezin.github.com # https://extensions.gnome.org/extension/3780/ddterm/
    dependencies:
      - vte3 # https://github.com/ddterm/gnome-shell-extension-ddterm/blob/0c337ee220dfe270ae6674ea0d41194a1d9d878c/ddterm/app/dependencies.json#L24
  # - id: gsconnect@andyholmes.github.io # https://extensions.gnome.org/extension/1319/gsconnect/
  # - id: gtktitlebar@velitasali.github.io # https://extensions.gnome.org/extension/1732/gtk-title-bar/
  # - id: executor@raujonas.github.io # https://extensions.gnome.org/extension/2932/executor/
  # - id: forge@jmmaranan.com # https://extensions.gnome.org/extension/4481/forge/
  - id: arch-update@RaphaelRochet # https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/
    dependencies:
      - pacman-contrib # arch-update extension requires "checkupdates" script from "pacman-contrib" package
      - gnome-console # kgx command
    settings:
      - schema: org.gnome.shell.extensions.arch-update
        key: update-cmd
        value: 'kgx -- /bin/sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read _" '
  # - id: dash-to-panel@jderose9.github.com  # use rocketbar instead
  # - id: disconnect-wifi@kgshank.net # https://extensions.gnome.org/extension/904/disconnect-wifi/
  # - id: PersianCalendar@oxygenws.com # https://extensions.gnome.org/extension/240/persian-calendar/
  - id: shamsi-calendar@gnome.scr.ir # https://extensions.gnome.org/extension/3618/shamsi-calendar/
  # - id: Vitals@CoreCoding.com # https://extensions.gnome.org/extension/1460/vitals/
  # - id: arcmenu@arcmenu.com # https://extensions.gnome.org/extension/3628/arcmenu/
  # - id: guillotine@fopdoodle.net # https://extensions.gnome.org/extension/3981/guillotine/
  # - id: no-overview@fthx # https://extensions.gnome.org/extension/4099/no-overview/

packages_pacman_extra:
  - nodejs
  - npm
  - sshuttle # VPN over SSH
  #- samba # for sharing file to windows or access files shared from windows
  #################################################### GUI ####################################################
  # - gimp
  # - inkscape
  # - firefox
  - meld
  - dconf-editor
  - uget
  ################################################## AppImage ##################################################
  - fuse2 # dependency for AppImage files (https://github.com/AppImage/AppImageKit/wiki/FUSE)
  #################################################### gvfs ####################################################
  - gvfs-mtp # Access Android over MTP (https://www.linuxfordevices.com/tutorials/linux/connect-android-to-arch-via-usb)
  - gvfs-smb # Access Windows shared folders (https://wiki.archlinux.org/title/Samba#File_manager_configuration)

packages_aur:
  - yay
  - nekoray-bin
  - pycharm-professional
  - microsoft-edge-stable-bin # Edge from Flatpak has some issues (e.g. system proxy does not work).
  # - freedownloadmanager # In FDM from Flatpak, browser integration does not work.
  - fstl # A fast STL file viewer
  - galaxybudsclient-bin # Unofficial Galaxy Buds Manager for Windows and Linux
  - try # Inspect a command's effects before modifying your live system (https://github.com/binpash/try)
  # - google-chrome # Chromium doesn't support Google sync, so I use Google Chrome.
  - visual-studio-code-bin
  - vale-bin # A markup-aware linter for prose

packages_flatpak:
  # - com.mattermost.Desktop  # Open Source Communication Platform
  # - org.freedownloadmanager.Manager  # Cross-platform Download Manager
  - com.transmissionbt.Transmission
  # - fr.handbrake.ghb
  # - org.keepassxc.KeePassXC
  - com.mattjakeman.ExtensionManager # Browse, install, and manage GNOME Shell Extensions
  - org.localsend.localsend_app # Share files to nearby devices.
  - com.bitwarden.desktop # A secure and free password manager for all of your devices
  - org.telegram.desktop # Instant Messaging
  - io.dbeaver.DBeaverCommunity # Universal Database Manager
  - org.libreoffice.LibreOffice # The LibreOffice productivity suite
  - com.ultimaker.cura # 3D Printing
  - com.github.marktext.marktext
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  # - io.bassi.Amberol  # Music Player
  # - com.redis.RedisInsight
  # - org.nickvision.tagger
  # - net.hovancik.Stretchly
  # - org.remmina.Remmina
